//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbParcel
    {
        public string Customer { get; set; }
        public decimal Transaction { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
