//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProduct
    {
        public int pcode { get; set; }
        public string pname { get; set; }
        public string ptype { get; set; }
        public string pcategory { get; set; }
        public int pqty { get; set; }
        public decimal pprice { get; set; }
    }
}
